/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

package wiringpi

import (
    //. "runtime/cgo"
    "unsafe"
)

type _ unsafe.Pointer

type _swig_fnptr *byte
type _swig_memberptr *byte

//extern wiringpiSwigCgocall
func SwigCgocall() {}

//extern wiringpiSwigCgocallDone
func SwigCgocallDone() {}

//extern wiringpiSwigCgocallBack
func SwigCgocallBack() {}

//extern wiringpiSwigCgocallBackDone
func SwigCgocallBackDone() {}

func WiringPiSetup() int          { return 0 }
func WiringPiSetupSys() int       { return 0 }
func WiringPiSetupGpio() int      { return 0 }
func WiringPiSetupPhys() int      { return 0 }
func PiFaceSetup(int) int         { return 0 }
func _swig_wrap_pinMode(int, int) {}

func PinMode(arg1 int, arg2 int) {
    _swig_wrap_pinMode(arg1, arg2)
}

func _swig_wrap_pullUpDnControl(int, int) {}

func PullUpDnControl(arg1 int, arg2 int) {
    _swig_wrap_pullUpDnControl(arg1, arg2)
}

func DigitalRead(int) int              { return 0 }
func _swig_wrap_digitalWrite(int, int) {}

func DigitalWrite(arg1 int, arg2 int) {
    _swig_wrap_digitalWrite(arg1, arg2)
}

func _swig_wrap_pwmWrite(int, int) {}

func PwmWrite(arg1 int, arg2 int) {
    _swig_wrap_pwmWrite(arg1, arg2)
}

func AnalogRead(int) int              { return 0 }
func _swig_wrap_analogWrite(int, int) {}

func AnalogWrite(arg1 int, arg2 int) {
    _swig_wrap_analogWrite(arg1, arg2)
}

func PiBoardRev() int                 { return 0 }
func WpiPinToGpio(int) int            { return 0 }
func _swig_wrap_setPadDrive(int, int) {}

func SetPadDrive(arg1 int, arg2 int) {
    _swig_wrap_setPadDrive(arg1, arg2)
}

func GetAlt(int) int                  { return 0 }
func _swig_wrap_digitalWriteByte(int) {}

func DigitalWriteByte(arg1 int) {
    _swig_wrap_digitalWriteByte(arg1)
}

func _swig_wrap_pwmSetMode(int) {}

func PwmSetMode(arg1 int) {
    _swig_wrap_pwmSetMode(arg1)
}

// func _swig_wrap_pwmSetRange(uint)

// func PwmSetRange(arg1 uint) {
//     _swig_wrap_pwmSetRange(arg1)
// }

// func _swig_wrap_pwmSetClock(int)

// func PwmSetClock(arg1 int) {
//     _swig_wrap_pwmSetClock(arg1)
// }

// func _swig_wrap_gpioClockSet(int, int)

// func GpioClockSet(arg1 int, arg2 int) {
//     _swig_wrap_gpioClockSet(arg1, arg2)
// }

// func _swig_wrap_waitForInterrupt_set(_swig_fnptr)

// func SetWaitForInterrupt(arg1 _swig_fnptr) {
//     _swig_wrap_waitForInterrupt_set(arg1)
// }

// func GetWaitForInterrupt() _swig_fnptr
// func WiringPiISR(int, int, _swig_fnptr) int
// func PiThreadCreate(_swig_fnptr) int
// func _swig_wrap_piLock(int)

// func PiLock(arg1 int) {
//     _swig_wrap_piLock(arg1)
// }

// func _swig_wrap_piUnlock(int)

// func PiUnlock(arg1 int) {
//     _swig_wrap_piUnlock(arg1)
// }

// func PiHiPri(int) int
// func _swig_wrap_delay(uint)

// func Delay(arg1 uint) {
//     _swig_wrap_delay(arg1)
// }

// func _swig_wrap_delayMicroseconds(uint)

// func DelayMicroseconds(arg1 uint) {
//     _swig_wrap_delayMicroseconds(arg1)
// }

// func Millis() uint
// func Micros() uint
// func SerialOpen(string, int) int
// func _swig_wrap_serialClose(int)

// func SerialClose(arg1 int) {
//     _swig_wrap_serialClose(arg1)
// }

// func _swig_wrap_serialFlush(int)

// func SerialFlush(arg1 int) {
//     _swig_wrap_serialFlush(arg1)
// }

// func _swig_wrap_serialPutchar(int, byte)

// func SerialPutchar(arg1 int, arg2 byte) {
//     _swig_wrap_serialPutchar(arg1, arg2)
// }

// func _swig_wrap_serialPuts(int, string)

// func SerialPuts(arg1 int, arg2 string) {
//     _swig_wrap_serialPuts(arg1, arg2)
// }

// func _swig_wrap_serialPrintf(int, string)

// func SerialPrintf(arg1 int, arg2 string) {
//     _swig_wrap_serialPrintf(arg1, arg2)
// }

// func SerialDataAvail(int) int
// func SerialGetchar(int) int
// func _swig_wrap_shiftOut(byte, byte, byte, byte)

// func ShiftOut(arg1 byte, arg2 byte, arg3 byte, arg4 byte) {
//     _swig_wrap_shiftOut(arg1, arg2, arg3, arg4)
// }

// func ShiftIn(byte, byte, byte) byte
// func WiringPiSPIGetFd(int) int
// func WiringPiSPIDataRW(int, string) int
// func WiringPiSPISetup(int, int) int
// func WiringPiI2CSetupInterface(string, int) int
// func WiringPiI2CSetup(int) int
// func WiringPiI2CRead(int) int
// func WiringPiI2CReadReg8(int, int) int
// func WiringPiI2CReadReg16(int, int) int
// func WiringPiI2CWrite(int, int) int
// func WiringPiI2CWriteReg8(int, int, int) int
// func WiringPiI2CWriteReg16(int, int, int) int
// func SoftToneCreate(int) int
// func _swig_wrap_softToneWrite(int, int)

// func SoftToneWrite(arg1 int, arg2 int) {
//     _swig_wrap_softToneWrite(arg1, arg2)
// }

// func _swig_wrap_softServoWrite(int, int)

// func SoftServoWrite(arg1 int, arg2 int) {
//     _swig_wrap_softServoWrite(arg1, arg2)
// }

// func SoftServoSetup(int, int, int, int, int, int, int, int) int
// func SoftPwmCreate(int, int, int) int
// func _swig_wrap_softPwmWrite(int, int)

// func SoftPwmWrite(arg1 int, arg2 int) {
//     _swig_wrap_softPwmWrite(arg1, arg2)
// }

// func Mcp23s17Setup(int, int, int) int
// func Mcp23017Setup(int, int) int
// func Mcp23s08Setup(int, int, int) int
// func Mcp23008Setup(int, int) int
// func Sr595Setup(int, int, int, int, int) int
// func _swig_wrap_lcdHome(int)

// func LcdHome(arg1 int) {
//     _swig_wrap_lcdHome(arg1)
// }

// func _swig_wrap_lcdClear(int)

// func LcdClear(arg1 int) {
//     _swig_wrap_lcdClear(arg1)
// }

// func _swig_wrap_lcdSendCommand(int, byte)

// func LcdSendCommand(arg1 int, arg2 byte) {
//     _swig_wrap_lcdSendCommand(arg1, arg2)
// }

// func _swig_wrap_lcdPosition(int, int, int)

// func LcdPosition(arg1 int, arg2 int, arg3 int) {
//     _swig_wrap_lcdPosition(arg1, arg2, arg3)
// }

// func _swig_wrap_lcdPutchar(int, byte)

// func LcdPutchar(arg1 int, arg2 byte) {
//     _swig_wrap_lcdPutchar(arg1, arg2)
// }

// func _swig_wrap_lcdPuts(int, string)

// func LcdPuts(arg1 int, arg2 string) {
//     _swig_wrap_lcdPuts(arg1, arg2)
// }

// func _swig_wrap_lcdPrintf(int, string)

// func LcdPrintf(arg1 int, arg2 string) {
//     _swig_wrap_lcdPrintf(arg1, arg2)
// }

// func LcdInit(int, int, int, int, int, int, int, int, int, int, int, int, int) int

// type SwigcptrVoid uintptr
// type Void interface {
//     Swigcptr() uintptr
// }

// func (p SwigcptrVoid) Swigcptr() uintptr {
//     return uintptr(p)
// }
