/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */
#define SWIGMODULE wiringPi
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct { char *p; int n; } _gostring_;
typedef struct { void* array; unsigned int len; unsigned int cap; } _goslice_;



#define SWIGGO_GCCGO

#ifdef __cplusplus
extern "C" {
#endif
extern void *_cgo_allocate(size_t);
extern void _cgo_panic(const char *);

/* Implementations of SwigCgocall and friends for different versions
   of gccgo.  The Go code will call these functions using C names with
   a prefix of the module name.  The implementations here call the
   routine in libgo.  The routines to call vary depending on the gccgo
   version.  We assume that the version of gcc used to compile this
   file is the same as the version of gccgo.  */

#define SWIGCONCAT2(s1, s2) s1 ## s2
#define SWIGCONCAT1(s1, s2) SWIGCONCAT2(s1, s2)
#define SwigCgocall SWIGCONCAT1(SWIGMODULE, SwigCgocall)
#define SwigCgocallDone SWIGCONCAT1(SWIGMODULE, SwigCgocallDone)
#define SwigCgocallBack SWIGCONCAT1(SWIGMODULE, SwigCgocallBack)
#define SwigCgocallBackDone SWIGCONCAT1(SWIGMODULE, SwigCgocallBackDone)

#define SWIG_GCC_VERSION \
  (__GNUC__ * 10000 + __GNUC_MINOR__ * 100 + __GNUC__PATH_LEVEL__)

#if SWIG_GCC_VERSION < 40700
#define SwigDoCgocall()
#define SwigDoCgocallDone()
#define SwigDoCgocallBack()
#define SwigDoCgocallBackDone()
#elif SWIG_GCC_VERSION == 40700
void SwigDoCgocall(void) __asm__("libgo_syscall.syscall.Entersyscall");
void SwigDoCgocallDone(void) __asm__("libgo_syscall.syscall.Exitsyscall");
void SwigDoCgocallBack(void) __asm__("libgo_syscall.syscall.Exitsyscall");
void SwigDoCgocallBackDone(void) __asm__("libgo_syscall.syscall.Entersyscall");
#else
void SwigDoCgocall(void) __asm__("syscall.Cgocall");
void SwigDoCgocallDone(void) __asm__("syscall.CgocallDone");
void SwigDoCgocallBack(void) __asm__("syscall.CgocallBack");
void SwigDoCgocallBackDone(void) __asm__("syscall.CgocallBackDone");
#endif

void SwigCgocall() {
  SwigDoCgocall();
}

void SwigCgocallDone() {
  SwigDoCgocallDone();
}

void SwigCgocallBack() {
  SwigDoCgocallBack();
}

void SwigCgocallBackDone() {
  SwigDoCgocallBackDone();
}

#ifdef __cplusplus
}
#endif

#define _swig_goallocate _cgo_allocate
#define _swig_gopanic _cgo_panic




static _gostring_ _swig_makegostring(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)_swig_goallocate(l + 1);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}

#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


#include "WiringPi/wiringPi/ds1302.h"
#include "WiringPi/wiringPi/gertboard.h"
#include "WiringPi/wiringPi/lcd.h"
#include "WiringPi/wiringPi/mcp23008.h"
#include "WiringPi/wiringPi/mcp23017.h"
#include "WiringPi/wiringPi/mcp23s08.h"
#include "WiringPi/wiringPi/mcp23s17.h"
#include "WiringPi/wiringPi/mcp23x0817.h"
#include "WiringPi/wiringPi/mcp23x08.h"
#include "WiringPi/wiringPi/piFace.h"
#include "WiringPi/wiringPi/piNes.h"
#include "WiringPi/wiringPi/softPwm.h"
#include "WiringPi/wiringPi/softServo.h"
#include "WiringPi/wiringPi/softTone.h"
#include "WiringPi/wiringPi/sr595.h"
#include "WiringPi/wiringPi/wiringPi.h"
#include "WiringPi/wiringPi/wiringPiI2C.h"
#include "WiringPi/wiringPi/wiringPiSPI.h"
#include "WiringPi/wiringPi/wiringSerial.h"
#include "WiringPi/wiringPi/wiringShift.h"

#ifdef __cplusplus
extern "C" {
#endif

int go__wrap_wiringPiSetup() {
  int result;
  int go_result;
  
  
  result = (int)wiringPiSetup();
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiSetupSys() {
  int result;
  int go_result;
  
  
  result = (int)wiringPiSetupSys();
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiSetupGpio() {
  int result;
  int go_result;
  
  
  result = (int)wiringPiSetupGpio();
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiSetupPhys() {
  int result;
  int go_result;
  
  
  result = (int)wiringPiSetupPhys();
  go_result = result; 
  return go_result;
}


int go__wrap_piFaceSetup(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)piFaceSetup(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_pinMode(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  pinMode(arg1,arg2);
  
}


void go__wrap_pullUpDnControl(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  pullUpDnControl(arg1,arg2);
  
}


int go__wrap_digitalRead(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)digitalRead(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_digitalWrite(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  digitalWrite(arg1,arg2);
  
}


void go__wrap_pwmWrite(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  pwmWrite(arg1,arg2);
  
}


int go__wrap_analogRead(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)analogRead(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_analogWrite(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  analogWrite(arg1,arg2);
  
}


int go__wrap_piBoardRev() {
  int result;
  int go_result;
  
  
  result = (int)piBoardRev();
  go_result = result; 
  return go_result;
}


int go__wrap_wpiPinToGpio(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)wpiPinToGpio(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_setPadDrive(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  setPadDrive(arg1,arg2);
  
}


int go__wrap_getAlt(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)getAlt(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_digitalWriteByte(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  digitalWriteByte(arg1);
  
}


void go__wrap_pwmSetMode(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  pwmSetMode(arg1);
  
}


void go__wrap_pwmSetRange(unsigned int garg1) {
  unsigned int arg1 ;
  
  arg1 = (unsigned int)garg1; 
  
  pwmSetRange(arg1);
  
}


void go__wrap_pwmSetClock(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  pwmSetClock(arg1);
  
}


void go__wrap_gpioClockSet(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  gpioClockSet(arg1,arg2);
  
}


void go__wrap_waitForInterrupt_set(void *garg1) {
  int (*arg1)(int,int) = (int (*)(int,int)) 0 ;
  
  arg1 = *(int (**)(int,int))&garg1; 
  
  waitForInterrupt = arg1;
  
}


void *go__wrap_waitForInterrupt_get() {
  int (*result)(int,int) = 0 ;
  void *go_result;
  
  
  result = (int (*)(int,int))waitForInterrupt;
  *(int (**)(int,int))&go_result = result; 
  return go_result;
}


int go__wrap_wiringPiISR(int garg1, int garg2, void *garg3) {
  int arg1 ;
  int arg2 ;
  void (*arg3)(void) = (void (*)(void)) 0 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = *(void (**)(void))&garg3; 
  
  result = (int)wiringPiISR(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


int go__wrap_piThreadCreate(void *garg1) {
  void *(*arg1)(void *) = (void *(*)(void *)) 0 ;
  int result;
  int go_result;
  
  arg1 = *(void *(**)(void *))&garg1; 
  
  result = (int)piThreadCreate(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_piLock(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  piLock(arg1);
  
}


void go__wrap_piUnlock(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  piUnlock(arg1);
  
}


int go__wrap_piHiPri(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)piHiPri(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_delay(unsigned int garg1) {
  unsigned int arg1 ;
  
  arg1 = (unsigned int)garg1; 
  
  delay(arg1);
  
}


void go__wrap_delayMicroseconds(unsigned int garg1) {
  unsigned int arg1 ;
  
  arg1 = (unsigned int)garg1; 
  
  delayMicroseconds(arg1);
  
}


unsigned int go__wrap_millis() {
  unsigned int result;
  unsigned int go_result;
  
  
  result = (unsigned int)millis();
  go_result = result; 
  return go_result;
}


unsigned int go__wrap_micros() {
  unsigned int result;
  unsigned int go_result;
  
  
  result = (unsigned int)micros();
  go_result = result; 
  return go_result;
}


int go__wrap_serialOpen(_gostring_ garg1, int garg2) {
  char *arg1 = (char *) 0 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (char *)garg1.p; 
  arg2 = (int)garg2; 
  
  result = (int)serialOpen(arg1,arg2);
  go_result = result; 
  return go_result;
}


void go__wrap_serialClose(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  serialClose(arg1);
  
}


void go__wrap_serialFlush(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  serialFlush(arg1);
  
}


void go__wrap_serialPutchar(int garg1, char garg2) {
  int arg1 ;
  unsigned char arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (unsigned char)garg2; 
  
  serialPutchar(arg1,arg2);
  
}


void go__wrap_serialPuts(int garg1, _gostring_ garg2) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (int)garg1; 
  arg2 = (char *)garg2.p; 
  
  serialPuts(arg1,arg2);
  
}


void go__wrap_serialPrintf(int garg1, _gostring_ garg2) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  void *arg3 = 0 ;
  
  arg1 = (int)garg1; 
  arg2 = (char *)garg2.p; 
  
  serialPrintf(arg1,arg2,arg3);
  
}


int go__wrap_serialDataAvail(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)serialDataAvail(arg1);
  go_result = result; 
  return go_result;
}


int go__wrap_serialGetchar(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)serialGetchar(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_shiftOut(char garg1, char garg2, char garg3, char garg4) {
  uint8_t arg1 ;
  uint8_t arg2 ;
  uint8_t arg3 ;
  uint8_t arg4 ;
  
  arg1 = (uint8_t)garg1; 
  arg2 = (uint8_t)garg2; 
  arg3 = (uint8_t)garg3; 
  arg4 = (uint8_t)garg4; 
  
  shiftOut(arg1,arg2,arg3,arg4);
  
}


char go__wrap_shiftIn(char garg1, char garg2, char garg3) {
  uint8_t arg1 ;
  uint8_t arg2 ;
  uint8_t arg3 ;
  uint8_t result;
  char go_result;
  
  arg1 = (uint8_t)garg1; 
  arg2 = (uint8_t)garg2; 
  arg3 = (uint8_t)garg3; 
  
  result = shiftIn(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiSPIGetFd(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)wiringPiSPIGetFd(arg1);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiSPIDataRW(int garg1, _gostring_ garg2) {
  int arg1 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  int arg3 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  {
    arg2 = (unsigned char *) PyString_AsString(garg2);
    arg3 = PyString_Size(garg2);
  }
  
  result = (int)wiringPiSPIDataRW(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiSPISetup(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  result = (int)wiringPiSPISetup(arg1,arg2);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CSetupInterface(_gostring_ garg1, int garg2) {
  char *arg1 = (char *) 0 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (char *)garg1.p; 
  arg2 = (int)garg2; 
  
  result = (int)wiringPiI2CSetupInterface(arg1,arg2);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CSetup(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)wiringPiI2CSetup(arg1);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CRead(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)wiringPiI2CRead(arg1);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CReadReg8(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  result = (int)wiringPiI2CReadReg8(arg1,arg2);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CReadReg16(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  result = (int)wiringPiI2CReadReg16(arg1,arg2);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CWrite(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  result = (int)wiringPiI2CWrite(arg1,arg2);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CWriteReg8(int garg1, int garg2, int garg3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  
  result = (int)wiringPiI2CWriteReg8(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


int go__wrap_wiringPiI2CWriteReg16(int garg1, int garg2, int garg3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  
  result = (int)wiringPiI2CWriteReg16(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


int go__wrap_softToneCreate(int garg1) {
  int arg1 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  
  result = (int)softToneCreate(arg1);
  go_result = result; 
  return go_result;
}


void go__wrap_softToneWrite(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  softToneWrite(arg1,arg2);
  
}


void go__wrap_softServoWrite(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  softServoWrite(arg1,arg2);
  
}


int go__wrap_softServoSetup(int garg1, int garg2, int garg3, int garg4, int garg5, int garg6, int garg7, int garg8) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  int arg8 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  arg4 = (int)garg4; 
  arg5 = (int)garg5; 
  arg6 = (int)garg6; 
  arg7 = (int)garg7; 
  arg8 = (int)garg8; 
  
  result = (int)softServoSetup(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8);
  go_result = result; 
  return go_result;
}


int go__wrap_softPwmCreate(int garg1, int garg2, int garg3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  
  result = (int)softPwmCreate(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


void go__wrap_softPwmWrite(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  softPwmWrite(arg1,arg2);
  
}


int go__wrap_mcp23s17Setup(int garg1, int garg2, int garg3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  
  result = (int)mcp23s17Setup(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


int go__wrap_mcp23017Setup(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  result = (int)mcp23017Setup(arg1,arg2);
  go_result = result; 
  return go_result;
}


int go__wrap_mcp23s08Setup(int garg1, int garg2, int garg3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  
  result = (int)mcp23s08Setup(arg1,arg2,arg3);
  go_result = result; 
  return go_result;
}


int go__wrap_mcp23008Setup(int garg1, int garg2) {
  int arg1 ;
  int arg2 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  
  result = (int)mcp23008Setup(arg1,arg2);
  go_result = result; 
  return go_result;
}


int go__wrap_sr595Setup(int garg1, int garg2, int garg3, int garg4, int garg5) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  arg4 = (int)garg4; 
  arg5 = (int)garg5; 
  
  result = (int)sr595Setup(arg1,arg2,arg3,arg4,arg5);
  go_result = result; 
  return go_result;
}


void go__wrap_lcdHome(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  lcdHome(arg1);
  
}


void go__wrap_lcdClear(int garg1) {
  int arg1 ;
  
  arg1 = (int)garg1; 
  
  lcdClear(arg1);
  
}


void go__wrap_lcdSendCommand(int garg1, char garg2) {
  int arg1 ;
  uint8_t arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (uint8_t)garg2; 
  
  lcdSendCommand(arg1,arg2);
  
}


void go__wrap_lcdPosition(int garg1, int garg2, int garg3) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  
  lcdPosition(arg1,arg2,arg3);
  
}


void go__wrap_lcdPutchar(int garg1, char garg2) {
  int arg1 ;
  uint8_t arg2 ;
  
  arg1 = (int)garg1; 
  arg2 = (uint8_t)garg2; 
  
  lcdPutchar(arg1,arg2);
  
}


void go__wrap_lcdPuts(int garg1, _gostring_ garg2) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  
  arg1 = (int)garg1; 
  arg2 = (char *)garg2.p; 
  
  lcdPuts(arg1,arg2);
  
}


void go__wrap_lcdPrintf(int garg1, _gostring_ garg2) {
  int arg1 ;
  char *arg2 = (char *) 0 ;
  void *arg3 = 0 ;
  
  arg1 = (int)garg1; 
  arg2 = (char *)garg2.p; 
  
  lcdPrintf(arg1,arg2,arg3);
  
}


int go__wrap_lcdInit(int garg1, int garg2, int garg3, int garg4, int garg5, int garg6, int garg7, int garg8, int garg9, int garg10, int garg11, int garg12, int garg13) {
  int arg1 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  int arg5 ;
  int arg6 ;
  int arg7 ;
  int arg8 ;
  int arg9 ;
  int arg10 ;
  int arg11 ;
  int arg12 ;
  int arg13 ;
  int result;
  int go_result;
  
  arg1 = (int)garg1; 
  arg2 = (int)garg2; 
  arg3 = (int)garg3; 
  arg4 = (int)garg4; 
  arg5 = (int)garg5; 
  arg6 = (int)garg6; 
  arg7 = (int)garg7; 
  arg8 = (int)garg8; 
  arg9 = (int)garg9; 
  arg10 = (int)garg10; 
  arg11 = (int)garg11; 
  arg12 = (int)garg12; 
  arg13 = (int)garg13; 
  
  result = (int)lcdInit(arg1,arg2,arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10,arg11,arg12,arg13);
  go_result = result; 
  return go_result;
}


#ifdef __cplusplus
}
#endif

